services:
  db:
    image: postgres:16

    environment:
      POSTGRES_USER: expense_tracker
      POSTGRES_PASSWORD: expense_tracker
      POSTGRES_DB: expense_tracker

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U expense_tracker -d expense_tracker",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: