"""add user ownership to expenses

Revision ID: 585326280b41
Revises: a9409d717d00
Create Date: 2026-07-21 15:12:00.252946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585326280b41'
down_revision: Union[str, None] = 'a9409d717d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_column('expenses', 'user_id')
    # ### end Alembic commands ###
