"""Add merchant to expenses

Revision ID: d85e711d8c93
Revises: 873ee0cb99f8
Create Date: 2026-07-13 15:54:40.152797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85e711d8c93'
down_revision: Union[str, None] = '873ee0cb99f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('merchant', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'merchant')
    # ### end Alembic commands ###
